### PR TITLE
Jn/str escape

### PR DESCRIPTION
**Pull request by musm**
Sorry I had  some git problems and accidently pushed to your branch.

### CODE REVIEW

**Comment by musm** [comment]
stale

**Comment by musm** [comment]
Fortunately for Powershell it looks like the situation will hopefully become vastly simpler in the future https://github.com/PowerShell/PowerShell/issues/13068

**Comment by vtjnash** [comment]
I forgot to turn on notifications, so not sure I'd seen this. Did you still want me to merge it? I've been meaning to resume writing at some point.

**Comment by musm** [comment]
If you want feel free to merge or not. I have no objections to either decision. I figured we might shelf this or something and was clearing stale PRs. I looked back at some of the escaping rules and the whole mess and might have puked a bit, lol, I don't remember half the rules anymore. Let me know what you think overall.

**Comment by musm** [comment]
merging this and we can iterate on it!

**Pull request merged**
